
services:
  db:
    image: postgres:16
    container_name: postgres_db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=mail@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    depends_on:
      - db
    volumes:
      - pgadmindata:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  pgdata:
  pgadmindata:

